# Generated by Django 2.0.1 on 2018-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180228_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(max_length=100, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.CharField(max_length=100, verbose_name='usuario'),
        ),
    ]
